### ISSUE TITLE
Enemies Group

### ISSUE THREAD

**Issue by sunzhaoyuan** [sunzhaoyuan/Live#1]
# Table of Contents
- [ ] [Milestone 1 Checklist](https://github.com/sunzhaoyuan/Live/issues/1#issuecomment-379368456)

**Comment by sunzhaoyuan** [comment]
112

**Comment by sunzhaoyuan** [comment]
## Milestone 1 - Due April 20th
- [ ] YoungKid
    - [x] Attack & Move
    - [ ] Collision
    - [ ] Animation
- [ ] Aniki
    - [ ] Attack & Move
    - [ ] Collision
    - [ ] Animation

**Comment by CurtisWang0325** [comment]
Making enemy AI: add nav Agent other stuffs to the game object. 
tutorials: https://docs.unity3d.com/Manual/Navigation.html
