### ISSUE TITLE
Player Group

### ISSUE THREAD

**Issue by Songloading** [sunzhaoyuan/Live#3]
Here is the working document for player group.

- [ ] [Milestone 1 Checklist](https://github.com/sunzhaoyuan/Live/issues/3#issuecomment-379366846)

**Comment by Songloading** [comment]
Here is a great tutorial for input by a joystick in unity:
https://www.youtube.com/watch?v=384_g0f7K_I
We probably will need to download a package, but it seems like not useable now:
https://assetstore.unity.com/packages/tools/input-management/cn-controls-joystick-touchpad-button-and-d-pad-15233

**Comment by CurtisWang0325** [comment]
Work:
Review prototype sections related to player
Learn tutorials for joystick input
Practicing unity’s third person controller
Downloaded a simple input controller- need a joystick to test
Plan:
Assign each joystick input to different functions
Learn about animation- actions for the player

**Comment by CurtisWang0325** [comment]
Way to put a third person controller into the scene:
1. import unity's standard character package.
2. Standard Assets-Characters-Third Person Controller-Prefabs-ThirdPersonController.prefab
3. Drag it onto a scene with ground.
4. wasd to move, c to squat, space to jump

**Comment by sunzhaoyuan** [comment]
## Milestone 1 - Due April 20th
- [ ] Finish Player's basic Moves
- [ ] Doge

_Full Key Mapping is in [Character Design Document](https://docs.google.com/document/d/1rhAnjwBi9XFK3qNYZqG6ZR5dG5z6DB8nasxMySo00-E/edit?usp=sharing) - "Character Animation List" section_

**Comment by CurtisWang0325** [comment]
Dodge animation
https://unity3d.com/learn/tutorials/topics/animation/humanoid-avatars?playlist=17099

**Comment by Songloading** [comment]
A link that is very useful for our player dodge movement:
https://forum.unity.com/threads/solved-scripting-a-dodge-skill-something-like-summoners-spell-flash-from-league-of-legends.389348/

**Comment by CurtisWang0325** [comment]
Week 5-6:

- [x] basic move

- [x] basic turn

- [x] aim

- [x] dodge

- [x] shoot

- [x] run/walk

**Comment by CurtisWang0325** [comment]
Input reference
![pasted image 0](https://user-images.githubusercontent.com/37714061/39101820-32e5da70-466c-11e8-9dd1-d4dfddfbe6b8.png)
LeftAnalogue: axis x, axis y (push= button 10)
RightAnalogue: Axis 3, Axis 6, (push =button 11)
button between these 2= button 12
TouchPad: button 13
L1:button 4
L2: button6
R1: button 5
R2: button 7
Square:button 0
cross: button 1
circle: button 2
triangle: button 3
Option: button 9
Share: button 8

**Comment by CurtisWang0325** [comment]
weak 6-7

- [x] raycast

- [x] shoot bondbullet

- [x] a line following bond

- [x] connect to the object while pressing l2

- [ ] add dodge, aiming, shooting feedback

- [ ] model/ animation of player

**Comment by Songloading** [comment]
weak 8-9

- [ ] basic move animation

- [x] shoot animation (fire/flash)

- [ ] sound effect

- [ ] grenade

- [x] shotgun bullet
